[2024-11-01T00:17:20.266-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-01T00:17:20.355-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_redshift_dag_variables_fed.load_to_redshift_task manual__2024-11-01T03:10:35.450292+00:00 [queued]>
[2024-11-01T00:17:20.417-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_redshift_dag_variables_fed.load_to_redshift_task manual__2024-11-01T03:10:35.450292+00:00 [queued]>
[2024-11-01T00:17:20.420-0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-01T00:17:20.534-0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_to_redshift_task> on 2024-11-01 03:10:35.450292+00:00
[2024-11-01T00:17:20.550-0300] {standard_task_runner.py:72} INFO - Started process 158042 to run task
[2024-11-01T00:17:20.569-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_redshift_dag_variables_fed', 'load_to_redshift_task', 'manual__2024-11-01T03:10:35.450292+00:00', '--job-id', '386', '--raw', '--subdir', 'DAGS_FOLDER/dag_variables_fed.py', '--cfg-path', '/tmp/tmp6ix8f5d7']
[2024-11-01T00:17:20.574-0300] {standard_task_runner.py:105} INFO - Job 386: Subtask load_to_redshift_task
[2024-11-01T00:17:21.380-0300] {task_command.py:467} INFO - Running <TaskInstance: etl_redshift_dag_variables_fed.load_to_redshift_task manual__2024-11-01T03:10:35.450292+00:00 [running]> on host DESKTOP-MVFODGC.
[2024-11-01T00:17:22.648-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_redshift_dag_variables_fed' AIRFLOW_CTX_TASK_ID='load_to_redshift_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-01T03:10:35.450292+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-01T03:10:35.450292+00:00'
[2024-11-01T00:17:22.690-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-01T00:17:22.725-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-01T00:17:22.749-0300] {logging_mixin.py:190} INFO - Current task name:load_to_redshift_task state:running start_date:2024-11-01 03:17:20.361364+00:00
[2024-11-01T00:17:22.778-0300] {logging_mixin.py:190} INFO - Dag name:etl_redshift_dag_variables_fed and current dag run status:running
[2024-11-01T00:17:22.802-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-01T00:17:22.828-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
TypeError: load_to_redshift_fed() missing 1 required positional argument: 'destination_table'
[2024-11-01T00:17:22.939-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-01T00:17:22.952-0300] {logging_mixin.py:190} INFO - Task start:2024-11-01 03:17:20.361364+00:00 end:2024-11-01 03:17:22.937699+00:00 duration:2.576335
[2024-11-01T00:17:22.964-0300] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_to_redshift_task> dag:<DAG: etl_redshift_dag_variables_fed> dagrun:<DagRun etl_redshift_dag_variables_fed @ 2024-11-01 03:10:35.450292+00:00: manual__2024-11-01T03:10:35.450292+00:00, state:running, queued_at: 2024-11-01 03:10:36.692961+00:00. externally triggered: True>
[2024-11-01T00:17:22.971-0300] {logging_mixin.py:190} INFO - Failure caused by load_to_redshift_fed() missing 1 required positional argument: 'destination_table'
[2024-11-01T00:17:22.977-0300] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_redshift_dag_variables_fed, task_id=load_to_redshift_task, run_id=manual__2024-11-01T03:10:35.450292+00:00, execution_date=20241101T031035, start_date=20241101T031720, end_date=20241101T031722
[2024-11-01T00:17:23.948-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-01T00:17:23.951-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 386 for task load_to_redshift_task (load_to_redshift_fed() missing 1 required positional argument: 'destination_table'; 158042)
Traceback (most recent call last):
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
TypeError: load_to_redshift_fed() missing 1 required positional argument: 'destination_table'
[2024-11-01T00:17:24.059-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-01T00:17:24.568-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-01T00:17:24.608-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
