[2024-11-01T00:17:42.726-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-01T00:17:42.770-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_redshift_dag_variables_fed.load_to_redshift_task scheduled__2024-10-30T19:00:00+00:00 [queued]>
[2024-11-01T00:17:42.808-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_redshift_dag_variables_fed.load_to_redshift_task scheduled__2024-10-30T19:00:00+00:00 [queued]>
[2024-11-01T00:17:42.811-0300] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-11-01T00:17:43.930-0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_to_redshift_task> on 2024-10-30 19:00:00+00:00
[2024-11-01T00:17:43.989-0300] {standard_task_runner.py:72} INFO - Started process 158139 to run task
[2024-11-01T00:17:44.010-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_redshift_dag_variables_fed', 'load_to_redshift_task', 'scheduled__2024-10-30T19:00:00+00:00', '--job-id', '387', '--raw', '--subdir', 'DAGS_FOLDER/dag_variables_fed.py', '--cfg-path', '/tmp/tmpbl8_8x0z']
[2024-11-01T00:17:44.063-0300] {standard_task_runner.py:105} INFO - Job 387: Subtask load_to_redshift_task
[2024-11-01T00:17:44.632-0300] {task_command.py:467} INFO - Running <TaskInstance: etl_redshift_dag_variables_fed.load_to_redshift_task scheduled__2024-10-30T19:00:00+00:00 [running]> on host DESKTOP-MVFODGC.
[2024-11-01T00:17:44.998-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_redshift_dag_variables_fed' AIRFLOW_CTX_TASK_ID='load_to_redshift_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-30T19:00:00+00:00'
[2024-11-01T00:17:45.002-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-01T00:17:45.007-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-01T00:17:45.010-0300] {logging_mixin.py:190} INFO - Current task name:load_to_redshift_task state:running start_date:2024-11-01 03:17:42.773615+00:00
[2024-11-01T00:17:45.013-0300] {logging_mixin.py:190} INFO - Dag name:etl_redshift_dag_variables_fed and current dag run status:running
[2024-11-01T00:17:45.015-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-01T00:17:45.019-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
TypeError: load_to_redshift_fed() missing 1 required positional argument: 'destination_table'
[2024-11-01T00:17:45.057-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-01T00:17:45.059-0300] {logging_mixin.py:190} INFO - Task start:2024-11-01 03:17:42.773615+00:00 end:2024-11-01 03:17:45.055996+00:00 duration:2.282381
[2024-11-01T00:17:45.062-0300] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_to_redshift_task> dag:<DAG: etl_redshift_dag_variables_fed> dagrun:<DagRun etl_redshift_dag_variables_fed @ 2024-10-30 19:00:00+00:00: scheduled__2024-10-30T19:00:00+00:00, state:running, queued_at: 2024-11-01 03:04:31.096810+00:00. externally triggered: False>
[2024-11-01T00:17:45.065-0300] {logging_mixin.py:190} INFO - Failure caused by load_to_redshift_fed() missing 1 required positional argument: 'destination_table'
[2024-11-01T00:17:45.068-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_redshift_dag_variables_fed, task_id=load_to_redshift_task, run_id=scheduled__2024-10-30T19:00:00+00:00, execution_date=20241030T190000, start_date=20241101T031742, end_date=20241101T031745
[2024-11-01T00:17:45.162-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-01T00:17:45.166-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 387 for task load_to_redshift_task (load_to_redshift_fed() missing 1 required positional argument: 'destination_table'; 158139)
Traceback (most recent call last):
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
TypeError: load_to_redshift_fed() missing 1 required positional argument: 'destination_table'
[2024-11-01T00:17:45.207-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-01T00:17:45.315-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-01T00:17:45.326-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
