[2024-10-31T01:17:20.530-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-31T01:17:20.581-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_redshift_dag_variables_bcra.extract_data manual__2024-10-30T23:12:51.658003+00:00 [queued]>
[2024-10-31T01:17:20.618-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_redshift_dag_variables_bcra.extract_data manual__2024-10-30T23:12:51.658003+00:00 [queued]>
[2024-10-31T01:17:20.622-0300] {taskinstance.py:2865} INFO - Starting attempt 3 of 4
[2024-10-31T01:17:20.714-0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_data> on 2024-10-30 23:12:51.658003+00:00
[2024-10-31T01:17:20.729-0300] {standard_task_runner.py:72} INFO - Started process 120831 to run task
[2024-10-31T01:17:20.741-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_redshift_dag_variables_bcra', 'extract_data', 'manual__2024-10-30T23:12:51.658003+00:00', '--job-id', '277', '--raw', '--subdir', 'DAGS_FOLDER/dag_variables_bcra.py', '--cfg-path', '/tmp/tmp97qm5g3z']
[2024-10-31T01:17:20.747-0300] {standard_task_runner.py:105} INFO - Job 277: Subtask extract_data
[2024-10-31T01:17:20.938-0300] {task_command.py:467} INFO - Running <TaskInstance: etl_redshift_dag_variables_bcra.extract_data manual__2024-10-30T23:12:51.658003+00:00 [running]> on host DESKTOP-MVFODGC.
[2024-10-31T01:17:21.263-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_redshift_dag_variables_bcra' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T23:12:51.658003+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-30T23:12:51.658003+00:00'
[2024-10-31T01:17:21.271-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-31T01:17:21.284-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-31T01:17:21.291-0300] {logging_mixin.py:190} INFO - Current task name:extract_data state:running start_date:2024-10-31 04:17:20.585851+00:00
[2024-10-31T01:17:21.296-0300] {logging_mixin.py:190} INFO - Dag name:etl_redshift_dag_variables_bcra and current dag run status:running
[2024-10-31T01:17:21.307-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-31T01:17:21.474-0300] {logging_mixin.py:190} WARNING - /home/nico/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1099 InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.bcra.gob.ar'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2024-10-31T01:17:21.525-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/dag_variables_bcra.py", line 45, in extract_task_callable
    df = extract_data(execution_date, variables_ids)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/../scripts/extract_data.py", line 31, in extract_data
    raise Exception(f"Error en la solicitud a la API. Código error: {response.status_code}")
Exception: Error en la solicitud a la API. Código error: 404
[2024-10-31T01:17:22.340-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-31T01:17:22.350-0300] {logging_mixin.py:190} INFO - Task start:2024-10-31 04:17:20.585851+00:00 end:2024-10-31 04:17:22.333409+00:00 duration:1.747558
[2024-10-31T01:17:22.360-0300] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_data> dag:<DAG: etl_redshift_dag_variables_bcra> dagrun:<DagRun etl_redshift_dag_variables_bcra @ 2024-10-30 23:12:51.658003+00:00: manual__2024-10-30T23:12:51.658003+00:00, state:running, queued_at: 2024-10-31 04:08:48.948187+00:00. externally triggered: True>
[2024-10-31T01:17:22.379-0300] {logging_mixin.py:190} INFO - Failure caused by Error en la solicitud a la API. Código error: 404
[2024-10-31T01:17:22.386-0300] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_redshift_dag_variables_bcra, task_id=extract_data, run_id=manual__2024-10-30T23:12:51.658003+00:00, execution_date=20241030T231251, start_date=20241031T041720, end_date=20241031T041722
[2024-10-31T01:17:22.532-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-31T01:17:22.537-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 277 for task extract_data (Error en la solicitud a la API. Código error: 404; 120831)
Traceback (most recent call last):
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/dag_variables_bcra.py", line 45, in extract_task_callable
    df = extract_data(execution_date, variables_ids)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/../scripts/extract_data.py", line 31, in extract_data
    raise Exception(f"Error en la solicitud a la API. Código error: {response.status_code}")
Exception: Error en la solicitud a la API. Código error: 404
[2024-10-31T01:17:22.613-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-31T01:17:22.712-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-31T01:17:22.719-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
