[2024-10-31T20:53:06.360-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-31T20:53:06.406-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_redshift_dag_variables_bcra.actualizar_dim_fecha scheduled__2024-10-30T19:00:00+00:00 [queued]>
[2024-10-31T20:53:06.448-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_redshift_dag_variables_bcra.actualizar_dim_fecha scheduled__2024-10-30T19:00:00+00:00 [queued]>
[2024-10-31T20:53:06.453-0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-31T20:53:06.542-0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): actualizar_dim_fecha> on 2024-10-30 19:00:00+00:00
[2024-10-31T20:53:06.558-0300] {standard_task_runner.py:72} INFO - Started process 147709 to run task
[2024-10-31T20:53:06.574-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_redshift_dag_variables_bcra', 'actualizar_dim_fecha', 'scheduled__2024-10-30T19:00:00+00:00', '--job-id', '338', '--raw', '--subdir', 'DAGS_FOLDER/dag_variables_bcra.py', '--cfg-path', '/tmp/tmpbmv3scji']
[2024-10-31T20:53:06.579-0300] {standard_task_runner.py:105} INFO - Job 338: Subtask actualizar_dim_fecha
[2024-10-31T20:53:06.833-0300] {task_command.py:467} INFO - Running <TaskInstance: etl_redshift_dag_variables_bcra.actualizar_dim_fecha scheduled__2024-10-30T19:00:00+00:00 [running]> on host DESKTOP-MVFODGC.
[2024-10-31T20:53:07.161-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_redshift_dag_variables_bcra' AIRFLOW_CTX_TASK_ID='actualizar_dim_fecha' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-30T19:00:00+00:00'
[2024-10-31T20:53:07.168-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-31T20:53:07.174-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-31T20:53:07.177-0300] {logging_mixin.py:190} INFO - Current task name:actualizar_dim_fecha state:running start_date:2024-10-31 23:53:06.411379+00:00
[2024-10-31T20:53:07.180-0300] {logging_mixin.py:190} INFO - Dag name:etl_redshift_dag_variables_bcra and current dag run status:running
[2024-10-31T20:53:07.183-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-31T20:53:18.261-0300] {logging_mixin.py:190} INFO - Error en la conexión o actualización de la tabla: ('communication error', gaierror(-3, 'Temporary failure in name resolution'))
[2024-10-31T20:53:18.309-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/../scripts/actualizar_dim_fecha.py", line 69, in actualizar_dim_fecha
    if conn is not None:
UnboundLocalError: local variable 'conn' referenced before assignment
[2024-10-31T20:53:18.442-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-31T20:53:18.449-0300] {logging_mixin.py:190} INFO - Task start:2024-10-31 23:53:06.411379+00:00 end:2024-10-31 23:53:18.440452+00:00 duration:12.029073
[2024-10-31T20:53:18.455-0300] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): actualizar_dim_fecha> dag:<DAG: etl_redshift_dag_variables_bcra> dagrun:<DagRun etl_redshift_dag_variables_bcra @ 2024-10-30 19:00:00+00:00: scheduled__2024-10-30T19:00:00+00:00, state:running, queued_at: 2024-10-31 23:52:54.752305+00:00. externally triggered: False>
[2024-10-31T20:53:18.468-0300] {logging_mixin.py:190} INFO - Failure caused by local variable 'conn' referenced before assignment
[2024-10-31T20:53:18.482-0300] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_redshift_dag_variables_bcra, task_id=actualizar_dim_fecha, run_id=scheduled__2024-10-30T19:00:00+00:00, execution_date=20241030T190000, start_date=20241031T235306, end_date=20241031T235318
[2024-10-31T20:53:18.864-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-31T20:53:18.867-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 338 for task actualizar_dim_fecha (local variable 'conn' referenced before assignment; 147709)
Traceback (most recent call last):
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/../scripts/actualizar_dim_fecha.py", line 69, in actualizar_dim_fecha
    if conn is not None:
UnboundLocalError: local variable 'conn' referenced before assignment
[2024-10-31T20:53:18.949-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-31T20:53:19.333-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-31T20:53:19.366-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
