[2024-10-28T19:50:17.324-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-28T19:50:17.378-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_redshift_dag_variables_bcra.limpieza_duplicados manual__2024-10-28T22:48:16.937843+00:00 [queued]>
[2024-10-28T19:50:17.427-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_redshift_dag_variables_bcra.limpieza_duplicados manual__2024-10-28T22:48:16.937843+00:00 [queued]>
[2024-10-28T19:50:17.430-0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-28T19:50:17.593-0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): limpieza_duplicados> on 2024-10-28 22:48:16.937843+00:00
[2024-10-28T19:50:17.616-0300] {standard_task_runner.py:72} INFO - Started process 37257 to run task
[2024-10-28T19:50:17.620-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_redshift_dag_variables_bcra', 'limpieza_duplicados', 'manual__2024-10-28T22:48:16.937843+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/dag_variables_bcra.py', '--cfg-path', '/tmp/tmpy6oru5mx']
[2024-10-28T19:50:17.623-0300] {standard_task_runner.py:105} INFO - Job 103: Subtask limpieza_duplicados
[2024-10-28T19:50:17.840-0300] {task_command.py:467} INFO - Running <TaskInstance: etl_redshift_dag_variables_bcra.limpieza_duplicados manual__2024-10-28T22:48:16.937843+00:00 [running]> on host DESKTOP-MVFODGC.
[2024-10-28T19:50:18.185-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_redshift_dag_variables_bcra' AIRFLOW_CTX_TASK_ID='limpieza_duplicados' AIRFLOW_CTX_EXECUTION_DATE='2024-10-28T22:48:16.937843+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-28T22:48:16.937843+00:00'
[2024-10-28T19:50:18.190-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-28T19:50:18.193-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-28T19:50:18.196-0300] {logging_mixin.py:190} INFO - Current task name:limpieza_duplicados state:running start_date:2024-10-28 22:50:17.384763+00:00
[2024-10-28T19:50:18.201-0300] {logging_mixin.py:190} INFO - Dag name:etl_redshift_dag_variables_bcra and current dag run status:running
[2024-10-28T19:50:18.204-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-28T19:50:20.447-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/../scripts/limpieza_duplicados.py", line 41, in limpieza_duplicados
    wr.redshift.execute_sql(delete_query, con=conn)
AttributeError: module 'awswrangler.redshift' has no attribute 'execute_sql'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/../scripts/limpieza_duplicados.py", line 45, in limpieza_duplicados
    raise Exception(f"Error en la limpieza de duplicados en Redshift: {e}")
Exception: Error en la limpieza de duplicados en Redshift: module 'awswrangler.redshift' has no attribute 'execute_sql'
[2024-10-28T19:50:20.502-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-28T19:50:20.506-0300] {logging_mixin.py:190} INFO - Task start:2024-10-28 22:50:17.384763+00:00 end:2024-10-28 22:50:20.501958+00:00 duration:3.117195
[2024-10-28T19:50:20.510-0300] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): limpieza_duplicados> dag:<DAG: etl_redshift_dag_variables_bcra> dagrun:<DagRun etl_redshift_dag_variables_bcra @ 2024-10-28 22:48:16.937843+00:00: manual__2024-10-28T22:48:16.937843+00:00, state:running, queued_at: 2024-10-28 22:48:17.160064+00:00. externally triggered: True>
[2024-10-28T19:50:20.513-0300] {logging_mixin.py:190} INFO - Failure caused by Error en la limpieza de duplicados en Redshift: module 'awswrangler.redshift' has no attribute 'execute_sql'
[2024-10-28T19:50:20.519-0300] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_redshift_dag_variables_bcra, task_id=limpieza_duplicados, run_id=manual__2024-10-28T22:48:16.937843+00:00, execution_date=20241028T224816, start_date=20241028T225017, end_date=20241028T225020
[2024-10-28T19:50:20.627-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-28T19:50:20.631-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 103 for task limpieza_duplicados (Error en la limpieza de duplicados en Redshift: module 'awswrangler.redshift' has no attribute 'execute_sql'; 37257)
Traceback (most recent call last):
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/../scripts/limpieza_duplicados.py", line 41, in limpieza_duplicados
    wr.redshift.execute_sql(delete_query, con=conn)
AttributeError: module 'awswrangler.redshift' has no attribute 'execute_sql'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/../scripts/limpieza_duplicados.py", line 45, in limpieza_duplicados
    raise Exception(f"Error en la limpieza de duplicados en Redshift: {e}")
Exception: Error en la limpieza de duplicados en Redshift: module 'awswrangler.redshift' has no attribute 'execute_sql'
[2024-10-28T19:50:20.669-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-28T19:50:20.729-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-28T19:50:20.737-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
