[2024-10-30T20:25:46.385-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-30T20:25:46.606-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_redshift_dag_variables_bcra.load_data manual__2024-10-28T01:18:28.390525+00:00 [queued]>
[2024-10-30T20:25:46.691-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_redshift_dag_variables_bcra.load_data manual__2024-10-28T01:18:28.390525+00:00 [queued]>
[2024-10-30T20:25:46.709-0300] {taskinstance.py:2865} INFO - Starting attempt 4 of 5
[2024-10-30T20:25:47.071-0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_data> on 2024-10-28 01:18:28.390525+00:00
[2024-10-30T20:25:47.093-0300] {standard_task_runner.py:72} INFO - Started process 89929 to run task
[2024-10-30T20:25:47.114-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_redshift_dag_variables_bcra', 'load_data', 'manual__2024-10-28T01:18:28.390525+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/dag_variables_bcra.py', '--cfg-path', '/tmp/tmpmslaqbj1']
[2024-10-30T20:25:47.125-0300] {standard_task_runner.py:105} INFO - Job 197: Subtask load_data
[2024-10-30T20:25:48.371-0300] {task_command.py:467} INFO - Running <TaskInstance: etl_redshift_dag_variables_bcra.load_data manual__2024-10-28T01:18:28.390525+00:00 [running]> on host DESKTOP-MVFODGC.
[2024-10-30T20:25:49.909-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_redshift_dag_variables_bcra' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-28T01:18:28.390525+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-28T01:18:28.390525+00:00'
[2024-10-30T20:25:49.914-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-30T20:25:49.917-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-30T20:25:49.920-0300] {logging_mixin.py:190} INFO - Current task name:load_data state:running start_date:2024-10-30 23:25:46.619234+00:00
[2024-10-30T20:25:49.923-0300] {logging_mixin.py:190} INFO - Dag name:etl_redshift_dag_variables_bcra and current dag run status:running
[2024-10-30T20:25:49.929-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-30T20:25:54.472-0300] {_write.py:249} ERROR - identifier must contain only alphanumeric characters, spaces, underscores, or hyphens
[2024-10-30T20:25:54.536-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/../scripts/load_to_redshift.py", line 41, in load_to_redshift
    wr.redshift.to_sql(
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/_utils.py", line 126, in inner
    return func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/_config.py", line 715, in wrapper
    return function(**args)
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/redshift/_write.py", line 200, in to_sql
    created_table, created_schema = _create_table(
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/redshift/_utils.py", line 397, in _create_table
    f"CREATE TABLE IF NOT EXISTS {_identifier(schema)}.{_identifier(table)} (\n"
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/redshift/_utils.py", line 33, in _identifier
    return _sql_utils.identifier(sql, sql_mode="ansi")
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/_sql_utils.py", line 30, in identifier
    raise exceptions.InvalidArgumentValue(
awswrangler.exceptions.InvalidArgumentValue: identifier must contain only alphanumeric characters, spaces, underscores, or hyphens

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/dag_variables_bcra.py", line 61, in load_task_callable
    load_to_redshift(df_transformado, conn_params)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/../scripts/load_to_redshift.py", line 55, in load_to_redshift
    raise Exception(f"Error en la conexi贸n o carga de datos a Redshift: {e}")
Exception: Error en la conexi贸n o carga de datos a Redshift: identifier must contain only alphanumeric characters, spaces, underscores, or hyphens
[2024-10-30T20:25:54.637-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-30T20:25:54.644-0300] {logging_mixin.py:190} INFO - Task start:2024-10-30 23:25:46.619234+00:00 end:2024-10-30 23:25:54.635648+00:00 duration:8.016414
[2024-10-30T20:25:54.650-0300] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_data> dag:<DAG: etl_redshift_dag_variables_bcra> dagrun:<DagRun etl_redshift_dag_variables_bcra @ 2024-10-28 01:18:28.390525+00:00: manual__2024-10-28T01:18:28.390525+00:00, state:running, queued_at: 2024-10-30 23:09:33.962545+00:00. externally triggered: True>
[2024-10-30T20:25:54.654-0300] {logging_mixin.py:190} INFO - Failure caused by Error en la conexi贸n o carga de datos a Redshift: identifier must contain only alphanumeric characters, spaces, underscores, or hyphens
[2024-10-30T20:25:54.661-0300] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_redshift_dag_variables_bcra, task_id=load_data, run_id=manual__2024-10-28T01:18:28.390525+00:00, execution_date=20241028T011828, start_date=20241030T232546, end_date=20241030T232554
[2024-10-30T20:25:54.883-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-30T20:25:54.900-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 197 for task load_data (Error en la conexi贸n o carga de datos a Redshift: identifier must contain only alphanumeric characters, spaces, underscores, or hyphens; 89929)
Traceback (most recent call last):
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/../scripts/load_to_redshift.py", line 41, in load_to_redshift
    wr.redshift.to_sql(
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/_utils.py", line 126, in inner
    return func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/_config.py", line 715, in wrapper
    return function(**args)
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/redshift/_write.py", line 200, in to_sql
    created_table, created_schema = _create_table(
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/redshift/_utils.py", line 397, in _create_table
    f"CREATE TABLE IF NOT EXISTS {_identifier(schema)}.{_identifier(table)} (\n"
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/redshift/_utils.py", line 33, in _identifier
    return _sql_utils.identifier(sql, sql_mode="ansi")
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/_sql_utils.py", line 30, in identifier
    raise exceptions.InvalidArgumentValue(
awswrangler.exceptions.InvalidArgumentValue: identifier must contain only alphanumeric characters, spaces, underscores, or hyphens

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/dag_variables_bcra.py", line 61, in load_task_callable
    load_to_redshift(df_transformado, conn_params)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/../scripts/load_to_redshift.py", line 55, in load_to_redshift
    raise Exception(f"Error en la conexi贸n o carga de datos a Redshift: {e}")
Exception: Error en la conexi贸n o carga de datos a Redshift: identifier must contain only alphanumeric characters, spaces, underscores, or hyphens
[2024-10-30T20:25:55.006-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-30T20:25:55.114-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-30T20:25:55.127-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
