[2024-11-03T19:11:40.469-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-03T19:11:40.524-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_redshift_dag_variables_fed.extract_data_fed_task scheduled__2024-11-01T22:00:00+00:00 [queued]>
[2024-11-03T19:11:40.564-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_redshift_dag_variables_fed.extract_data_fed_task scheduled__2024-11-01T22:00:00+00:00 [queued]>
[2024-11-03T19:11:40.566-0300] {taskinstance.py:2865} INFO - Starting attempt 11 of 11
[2024-11-03T19:11:40.713-0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_data_fed_task> on 2024-11-01 22:00:00+00:00
[2024-11-03T19:11:40.730-0300] {standard_task_runner.py:72} INFO - Started process 226676 to run task
[2024-11-03T19:11:40.756-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_redshift_dag_variables_fed', 'extract_data_fed_task', 'scheduled__2024-11-01T22:00:00+00:00', '--job-id', '604', '--raw', '--subdir', 'DAGS_FOLDER/dag_variables_fed.py', '--cfg-path', '/tmp/tmpwuxhjnbs']
[2024-11-03T19:11:40.763-0300] {standard_task_runner.py:105} INFO - Job 604: Subtask extract_data_fed_task
[2024-11-03T19:11:41.128-0300] {task_command.py:467} INFO - Running <TaskInstance: etl_redshift_dag_variables_fed.extract_data_fed_task scheduled__2024-11-01T22:00:00+00:00 [running]> on host DESKTOP-MVFODGC.
[2024-11-03T19:11:42.959-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_redshift_dag_variables_fed' AIRFLOW_CTX_TASK_ID='extract_data_fed_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-01T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-01T22:00:00+00:00'
[2024-11-03T19:11:43.094-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-03T19:11:43.159-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-03T19:11:43.231-0300] {logging_mixin.py:190} INFO - Current task name:extract_data_fed_task state:running start_date:2024-11-03 22:11:40.527439+00:00
[2024-11-03T19:11:43.277-0300] {logging_mixin.py:190} INFO - Dag name:etl_redshift_dag_variables_fed and current dag run status:running
[2024-11-03T19:11:43.286-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-03T19:11:44.273-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/../scripts/extract_data_fed.py", line 89, in extract_data_fed
    df= process_to_dataframe(data, series_id)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/../scripts/extract_data_fed.py", line 64, in process_to_dataframe
    df['value'] = df['value'].astype('float64')
  File "/home/nico/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 6643, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/home/nico/.local/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 430, in astype
    return self.apply(
  File "/home/nico/.local/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 363, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/pandas/core/internals/blocks.py", line 758, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/home/nico/.local/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 237, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/home/nico/.local/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 182, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File "/home/nico/.local/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 133, in _astype_nansafe
    return arr.astype(dtype, copy=True)
ValueError: could not convert string to float: '.'
[2024-11-03T19:11:44.325-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-03T19:11:44.330-0300] {logging_mixin.py:190} INFO - Task start:2024-11-03 22:11:40.527439+00:00 end:2024-11-03 22:11:44.323883+00:00 duration:3.796444
[2024-11-03T19:11:44.337-0300] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_data_fed_task> dag:<DAG: etl_redshift_dag_variables_fed> dagrun:<DagRun etl_redshift_dag_variables_fed @ 2024-11-01 22:00:00+00:00: scheduled__2024-11-01T22:00:00+00:00, state:running, queued_at: 2024-11-03 22:08:28.881659+00:00. externally triggered: False>
[2024-11-03T19:11:44.342-0300] {logging_mixin.py:190} INFO - Failure caused by could not convert string to float: '.'
[2024-11-03T19:11:44.347-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_redshift_dag_variables_fed, task_id=extract_data_fed_task, run_id=scheduled__2024-11-01T22:00:00+00:00, execution_date=20241101T220000, start_date=20241103T221140, end_date=20241103T221144
[2024-11-03T19:11:44.460-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-03T19:11:44.464-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 604 for task extract_data_fed_task (could not convert string to float: '.'; 226676)
Traceback (most recent call last):
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/../scripts/extract_data_fed.py", line 89, in extract_data_fed
    df= process_to_dataframe(data, series_id)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/../scripts/extract_data_fed.py", line 64, in process_to_dataframe
    df['value'] = df['value'].astype('float64')
  File "/home/nico/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 6643, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/home/nico/.local/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 430, in astype
    return self.apply(
  File "/home/nico/.local/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 363, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/pandas/core/internals/blocks.py", line 758, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/home/nico/.local/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 237, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/home/nico/.local/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 182, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File "/home/nico/.local/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 133, in _astype_nansafe
    return arr.astype(dtype, copy=True)
ValueError: could not convert string to float: '.'
[2024-11-03T19:11:44.504-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-03T19:11:44.594-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-03T19:11:44.670-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
